# Generated by Django 3.1.5 on 2021-01-21 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('FD', 'Food and drinks'), ('BP', 'Bars, pubs and clubs'), ('OD', 'Outdoor acitvities'), ('SE', 'Sports and exercises'), ('OT', 'Others')], max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, default='Add a description', null=True)),
            ],
        ),
    ]
