# Generated by Django 3.1.5 on 2021-01-21 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
