# Generated by Django 3.1.5 on 2021-01-21 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangout', '0003_remove_hangout_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangout',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='hangout_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hangout',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
