# Generated by Django 3.1.5 on 2021-01-21 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hangout', '0004_auto_20210121_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owned_hangout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='participants',
            field=models.ManyToManyField(related_name='participating_hangout', to=settings.AUTH_USER_MODEL),
        ),
    ]
